
#General settings
[general]
	#Maximum lives a player can have before being "banned".
	#Range: > 1
	maxLives = 3
	#Ban type once the player dies too many times.
	#Accepts: SPECTATOR, BAN
	#Allowed Values: SPECTATOR, BAN
	banType = "SPECTATOR"
	#Length of time the player is banned (in seconds). Set to 0 to permaban.
	#Range: > 0
	banTime = 300
	#How much health to change per death.
	#Range: -20.0 ~ 20.0
	healthAdjust = 0.0
	#What's the maximum health reduction allowed before it caps out? Set to 0 to disable cap.
	#Range: -500.0 ~ 0.0
	maxHealthReduction = 0.0
	#Should we announce the player their remaining lives on respawn?
	announceOnRespawn = true

